added conditional download resume feature
arifszn/gitprofile pull request #179
Opened 2022-10-02 12:04 UTC by joanjeremiah

I have implemented 'Download Resume' feature . Just let me know if any changes required

2022-10-02 13:19 UTC, arifszn requested changes
Thanks for the PR. A small modification is required. Also, please update the readme.

2022-10-02 13:19 UTC, arifszn commented on src/components/avatar-card/index.jsx
> +          <a href= { resume.fileName } target="_blank" className='btn mt-4' download>Download my resume</a>
```suggestion
          <a
            href={resume.fileName}
            target="_blank"
            className="btn btn-outline btn-primary text-xs mt-6"
            download
          >
            Download Resume
          </a>
```

2022-10-02 16:42 UTC, joanjeremiah reviewed
I made the suggested changes in the 'Download Resume' button and also update the readme markdown.

2022-10-03 08:35 UTC, arifszn commented
Looks good. Can you please run the command `npm run lint:fix:`? Also, are you participating in `hacktoberfest`? Do I need to do anything after merging it so that it counts against you?

2022-10-03 09:04 UTC, joanjeremiah commented
> Looks good. Can you please run the command `npm run lint:fix:`? Also, are you participating in `hacktoberfest`? Do I need to do anything after merging it so that it counts against you?

I have run the lint fix command. Do I need to make another pull request ? And yes I am participating in `hacktoberfest` . I believe simply merging my pull request is enough for it to count . I will let you know if it was not taken into the count.

2022-10-03 09:09 UTC, joanjeremiah commented
I don't know why the `run prettier` command fails . Please let me know what I need to do.

2022-10-03 09:14 UTC, arifszn commented
> I don't know why the `run prettier` command fails . Please let me know what I need to do.

Maybe try running `npm run prettier:fix`.

2022-10-03 09:28 UTC, merged

2022-10-03 09:28 UTC, joanjeremiah commented
> > I don't know why the `run prettier` command fails . Please let me know what I need to do.
> 
> Maybe try running `npm run prettier:fix`.

I tried running the command and it works !