Allow CRLF when linting #198
arifszn/gitprofile pull request #228
Opened 2022-10-27 11:39 UTC by knittl

We should still detect mixed/inconsistent CRLF when linting in the CI at GitHub. Perhaps we can read an environment variable to enable/disable this feature for local linting and CI linting.

2022-10-27 11:43 UTC, arifszn requested changes
We should move the rule to `.prettierrc` file.

```
"endOfLine": "auto"
```

2022-10-27 12:02 UTC, knittl commented
> We should move the rule to `.prettierrc` file.
> 
> ```
> "endOfLine": "auto"
> ```

Happy to oblige. But I'm a bit confused and want to better understand why a/the change is done. The source of #198 was <https://github.com/arifszn/gitprofile/pull/196#issuecomment-1278954711> which mentioned adding the rule to `.eslintrc.js`.

1. What is the difference between `npm run lint` and `npm run prettier`? Why are there two commands to do pretty (no pun intended) much the same?
2. CRLF in commits will no longer be forbidden when linting PRs. Is this OK and intended?
3. Configuring this in `.eslintrc.js` allows to conditionally enable it, based on the value of `process.env.CI`. CI lint could disallow CRLF, while linting locally would ignore them. `.prettierrc` seems to be static JSON.

I want to avoid introducing hard-to-detect inconsistencies.

2022-10-27 16:47 UTC, knittl commented
In any case, moved the setting to `.prettierrc` file for now.

2022-10-28 05:29 UTC, arifszn commented
1. Lint shares the same config as the prettier on top of its own linting rules. The goal was to use one command (`npm run lint`) for prettier and lining both. `npm run prettier` remains for reference. 
2. Yes, we will allow both CRLF and LF.
3. https://www.loom.com/share/752e7d17ea2948989cf6bbc63c8fe886. This video was recorded on a windows machine. As you see, if I clone the repo, and open the code editor, it gives errors for the end of the line. Also, running `npm run lint` will show errors for the `endOfLine`. Windows uses CRLF while cloning the repo. Sure, an advanced user knows how to bypass it but assuming the contributors are newcomers, I want to make the contribution as simple as possible.
  If we introduce conditional checking, the PR will also fail pushed from a windows machine.

2022-10-29 08:16 UTC, arifszn approved these changes

2022-10-29 08:16 UTC, merged